# Generated by Django 5.1.7 on 2025-04-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattendance',
            name='present_students',
            field=models.ManyToManyField(related_name='attendances', to='students.student'),
        ),
    ]
