# Generated by Django 5.1.7 on 2025-04-22 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classattendance',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classdocument',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='superuser_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.superuser'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', to='students.student'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classes', to='students.subject'),
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='classdocument',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='schoolstream',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schools.school'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='schools.schoolstream'),
        ),
        migrations.AlterUniqueTogether(
            name='classattendance',
            unique_together={('school_class', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolstream',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'school', 'academic_year')},
        ),
    ]
