# Generated by Django 5.1.7 on 2025-04-08 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
        ('users', '0002_superuser_phone_number_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(default='SKUD000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='level',
            field=models.CharField(default='Primary', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='superuser_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.superuser'),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(default='0700000000', max_length=15),
        ),
    ]
