# Generated by Django 5.1.7 on 2025-04-30 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'permissions': [('manage_school', 'Can manage all school operations'), ('view_dashboard', 'Can view school dashboard')]},
        ),
        migrations.RenameField(
            model_name='school',
            old_name='description',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='created_at',
            new_name='registration_date',
        ),
        migrations.RemoveField(
            model_name='school',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='school',
            name='level',
        ),
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
        migrations.RemoveField(
            model_name='school',
            name='superuser_profile',
        ),
        migrations.AddField(
            model_name='school',
            name='academic_year_structure',
            field=models.CharField(choices=[('SEMESTER', 'Semester'), ('TERM', 'Term'), ('QUARTER', 'Quarter')], default='TERM', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='founded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='schooladmin',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='administered_school', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(default='Africa/Nairobi', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('PRE', 'Pre-school'), ('PRI', 'Primary'), ('SEC', 'Secondary'), ('HS', 'High School')], default='PRI', max_length=3),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
