# Generated by Django 5.1.7 on 2025-05-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_current_school_year_school_current_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
