# Generated by Django 5.1.7 on 2025-05-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_school_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
