# Generated by Django 5.1.7 on 2025-05-07 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_school_schooladmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='schooladmin',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='administered_school', to=settings.AUTH_USER_MODEL),
        ),
    ]
