# Generated by Django 5.1.7 on 2025-05-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_schoolclass_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattendance',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
