# Generated by Django 5.1.7 on 2025-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_alter_school_schooladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='po_box',
            field=models.CharField(blank=True, help_text='P.O. Box address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, help_text='School website URL', null=True),
        ),
    ]
