# Generated by Django 5.1.7 on 2025-04-15 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('general', 'General'), ('meeting', 'Meeting'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('announcement', 'Announcement')], default='general', max_length=20)),
                ('is_for_all_teachers', models.BooleanField(default=False)),
                ('is_for_all_parents', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='event_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('targeted_parents', models.ManyToManyField(blank=True, related_name='parent_events', to=settings.AUTH_USER_MODEL)),
                ('targeted_teachers', models.ManyToManyField(blank=True, related_name='teacher_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
