# Generated by Django 5.1.7 on 2025-04-29 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        ('schools', '0003_initial'),
        ('users', '0005_remove_parent_receive_sms_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Going'), ('not_going', 'Not Going'), ('maybe', 'Maybe')], default='going', max_length=20)),
                ('response_note', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event RSVP',
                'verbose_name_plural': 'Event RSVPs',
            },
        ),
        migrations.AlterModelOptions(
            name='schoolevent',
            options={'ordering': ['-start_datetime']},
        ),
        migrations.RenameField(
            model_name='schoolevent',
            old_name='is_for_all_parents',
            new_name='is_all_day',
        ),
        migrations.RenameField(
            model_name='schoolevent',
            old_name='is_for_all_teachers',
            new_name='requires_rsvp',
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='rsvp_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.school'),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='target_type',
            field=models.CharField(choices=[('all', 'Everyone'), ('teachers', 'Teachers'), ('parents', 'Parents'), ('specific', 'Specific Users'), ('classes', 'Specific Classes')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='targeted_classes',
            field=models.ManyToManyField(blank=True, related_name='class_events', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='event_type',
            field=models.CharField(choices=[('general', 'General'), ('meeting', 'Meeting'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('announcement', 'Announcement'), ('parent_event', 'Parent Event'), ('staff_event', 'Staff Event')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='targeted_parents',
            field=models.ManyToManyField(blank=True, related_name='parent_events', to='users.parent'),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='targeted_teachers',
            field=models.ManyToManyField(blank=True, related_name='teacher_events', to='users.teacher'),
        ),
        migrations.AddIndex(
            model_name='schoolevent',
            index=models.Index(fields=['start_datetime'], name='scheduler_s_start_d_7b39c7_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolevent',
            index=models.Index(fields=['end_datetime'], name='scheduler_s_end_dat_5ee1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolevent',
            index=models.Index(fields=['event_type'], name='scheduler_s_event_t_334bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolevent',
            index=models.Index(fields=['target_type'], name='scheduler_s_target__779873_idx'),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='scheduler.schoolevent'),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together={('event', 'user')},
        ),
    ]
