# Generated by Django 5.1.7 on 2025-04-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_schoolevent_school'),
        ('schools', '0004_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolevent',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.school'),
        ),
    ]
