# Generated by Django 5.1.7 on 2025-05-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_schoolevent_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolevent',
            name='current_school_year',
        ),
        migrations.RemoveField(
            model_name='schoolevent',
            name='current_term',
        ),
    ]
