# Generated by Django 5.1.7 on 2025-08-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_remove_schoolevent_current_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolevent',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
