# Generated by Django 5.1.7 on 2025-07-29 11:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('schools', '0013_alter_school_schooladmin'),
        ('students', '0004_studentattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_grade', models.CharField(max_length=10)),
                ('overall_position', models.PositiveIntegerField()),
                ('details', models.JSONField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_reports', to='schools.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_reports', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year', 'term', 'overall_position'],
                'unique_together': {('student', 'school_class', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ExamConsolidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in percentage for this exam type', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_rules', to='exams.examtype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_rules', to='schools.school')),
            ],
            options={
                'ordering': ['-weight'],
                'unique_together': {('school', 'exam_type')},
            },
        ),
    ]
