# Generated by Django 5.1.7 on 2025-05-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsalert',
            name='alert_type',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance Alert'), ('PERFORMANCE', 'Performance Alert'), ('REPORT', 'Report Alert'), ('DOCUMENT', 'Document Alert'), ('ABSENCE_NO_NOTES', 'Absence Without Notes Alert'), ('SYSTEM', 'System Alert')], max_length=20),
        ),
    ]
