# Generated by Django 5.1.7 on 2025-04-29 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Action Log', 'verbose_name_plural': 'Action Logs'},
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='action_by_parent',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='action_by_superuser',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='action_by_teacher',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='category',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('SHARE', 'Share'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user_tag',
            field=models.UUIDField(editable=False),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['-timestamp'], name='action_logs_timesta_69b004_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['user'], name='action_logs_user_id_1dbdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['category'], name='action_logs_categor_d9b647_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['content_type', 'object_id'], name='action_logs_content_039c98_idx'),
        ),
    ]
