# Generated by Django 5.1.7 on 2025-05-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0002_alter_actionlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
