# Generated by Django 5.1.7 on 2025-07-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0004_alter_actionlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='category',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('SHARE', 'Share'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
