# Generated by Django 5.1.7 on 2025-07-30 10:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0013_alter_school_schooladmin'),
        ('students', '0004_studentattendance'),
        ('users', '0015_alter_administratorprofile_date_appointed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KCSEResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1989), django.core.validators.MaxValueValidator(2025)])),
                ('index_number', models.CharField(max_length=20)),
                ('mean_grade', models.CharField(choices=[('A', 'A (80-100)'), ('A-', 'A- (75-79)'), ('B+', 'B+ (70-74)'), ('B', 'B (65-69)'), ('B-', 'B- (60-64)'), ('C+', 'C+ (55-59)'), ('C', 'C (50-54)'), ('C-', 'C- (45-49)'), ('D+', 'D+ (40-44)'), ('D', 'D (35-39)'), ('D-', 'D- (30-34)'), ('E', 'E (0-29)')], max_length=2)),
                ('mean_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('division', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kcse_results', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kcse_results', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KCSE Result',
                'verbose_name_plural': 'KCSE Results',
                'ordering': ['-year', 'student__last_name'],
                'unique_together': {('school', 'student', 'year')},
            },
        ),
        migrations.CreateModel(
            name='KCSESchoolPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1989), django.core.validators.MaxValueValidator(2025)])),
                ('mean_grade', models.CharField(choices=[('A', 'A (80-100)'), ('A-', 'A- (75-79)'), ('B+', 'B+ (70-74)'), ('B', 'B (65-69)'), ('B-', 'B- (60-64)'), ('C+', 'C+ (55-59)'), ('C', 'C (50-54)'), ('C-', 'C- (45-49)'), ('D+', 'D+ (40-44)'), ('D', 'D (35-39)'), ('D-', 'D- (30-34)'), ('E', 'E (0-29)')], max_length=2)),
                ('mean_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_students', models.PositiveIntegerField()),
                ('university_qualified', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kcse_performances', to='schools.school')),
            ],
            options={
                'verbose_name': 'KCSE School Performance',
                'verbose_name_plural': 'KCSE School Performances',
                'ordering': ['-year'],
                'unique_together': {('school', 'year')},
            },
        ),
        migrations.CreateModel(
            name='KCSESubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('mean_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mean_grade', models.CharField(choices=[('A', 'A (80-100)'), ('A-', 'A- (75-79)'), ('B+', 'B+ (70-74)'), ('B', 'B (65-69)'), ('B-', 'B- (60-64)'), ('C+', 'C+ (55-59)'), ('C', 'C (50-54)'), ('C-', 'C- (45-49)'), ('D+', 'D+ (40-44)'), ('D', 'D (35-39)'), ('D-', 'D- (30-34)'), ('E', 'E (0-29)')], max_length=2)),
                ('total_students', models.PositiveIntegerField()),
                ('entered', models.PositiveIntegerField()),
                ('passed', models.PositiveIntegerField()),
                ('school_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='kcse.kcseschoolperformance')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
                ('subject_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher')),
            ],
            options={
                'verbose_name': 'KCSE Subject Performance',
                'verbose_name_plural': 'KCSE Subject Performances',
                'unique_together': {('school_performance', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='KCSESubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('grade', models.CharField(choices=[('A', 'A (80-100)'), ('A-', 'A- (75-79)'), ('B+', 'B+ (70-74)'), ('B', 'B (65-69)'), ('B-', 'B- (60-64)'), ('C+', 'C+ (55-59)'), ('C', 'C (50-54)'), ('C-', 'C- (45-49)'), ('D+', 'D+ (40-44)'), ('D', 'D (35-39)'), ('D-', 'D- (30-34)'), ('E', 'E (0-29)')], max_length=2)),
                ('points', models.PositiveSmallIntegerField()),
                ('mean_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mean_grade', models.CharField(blank=True, choices=[('A', 'A (80-100)'), ('A-', 'A- (75-79)'), ('B+', 'B+ (70-74)'), ('B', 'B (65-69)'), ('B-', 'B- (60-64)'), ('C+', 'C+ (55-59)'), ('C', 'C (50-54)'), ('C-', 'C- (45-49)'), ('D+', 'D+ (40-44)'), ('D', 'D (35-39)'), ('D-', 'D- (30-34)'), ('E', 'E (0-29)')], max_length=2, null=True)),
                ('kcse_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='kcse.kcseresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
                ('subject_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher')),
            ],
            options={
                'verbose_name': 'KCSE Subject Result',
                'verbose_name_plural': 'KCSE Subject Results',
                'unique_together': {('kcse_result', 'subject')},
            },
        ),
    ]
