# Generated by Django 4.2.27 on 2025-12-24 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcsesubjectperformance',
            name='year',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1989), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
