# Generated by Django 5.1.7 on 2025-04-28 12:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentdocument_studentnote_studentstatuschange_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused Absence')], default='PRESENT', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for absence or late arrival', null=True)),
                ('time_in', models.TimeField(blank=True, help_text='Time student arrived if late', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ['-date', 'student__first_name'],
                'indexes': [models.Index(fields=['student', 'date'], name='students_st_student_8ce0c9_idx'), models.Index(fields=['date', 'status'], name='students_st_date_397d70_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
