# Generated by Django 5.1.7 on 2025-11-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='periods_per_week',
            field=models.PositiveIntegerField(default=5, help_text='Number of periods per week'),
        ),
    ]
