# Generated by Django 5.1.7 on 2025-11-25 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_subject_periods_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kcpe_marks',
            field=models.IntegerField(blank=True, help_text='KCPE examination marks', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text="Student's photograph", null=True, upload_to='students/photos/'),
        ),
    ]
