# Generated by Django 5.1.7 on 2025-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='preferred_format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('HTML', 'HTML')], default='PDF', max_length=10),
        ),
    ]
