# Generated by Django 5.1.7 on 2025-05-19 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reporttemplate_preferred_format'),
        ('users', '0012_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termreportrequest',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parent'),
        ),
    ]
