# Generated by Django 5.1.7 on 2025-05-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_termreportrequest_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='term',
            field=models.CharField(max_length=40),
        ),
    ]
