# Generated by Django 5.1.7 on 2025-12-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_academicrecord_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='end_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='End-term exam score (typically 60%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='entry_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry exam score (typically 20%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='mid_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mid-term exam score (typically 20%)', max_digits=5, null=True),
        ),
    ]
