# Generated by Django 5.1.7 on 2025-04-22 07:57

import django.db.models.deletion
import skul_data.documents.models.document
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_initial'),
        ('students', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=skul_data.documents.models.document.document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('file_size', models.PositiveIntegerField(default=0, editable=False)),
                ('file_type', models.CharField(default='', editable=False, max_length=50)),
                ('allowed_roles', models.ManyToManyField(blank=True, help_text='Roles that can access this document', to='users.role')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Specific users who can access this document', related_name='allowed_documents', to=settings.AUTH_USER_MODEL)),
                ('related_class', models.ForeignKey(blank=True, help_text='Optional: Class this document is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.schoolclass')),
                ('related_students', models.ManyToManyField(blank=True, help_text='Optional: Students this document is associated with', to='students.student')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'permissions': [('bulk_delete_document', 'Can bulk delete documents'), ('bulk_download_document', 'Can bulk download documents')],
            },
        ),
        migrations.CreateModel(
            name='DocumentShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('download_limit', models.PositiveIntegerField(blank=True, help_text='Optional: Limit number of downloads', null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
    ]
