# Generated by Django 5.1.7 on 2025-05-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
