# Generated by Django 5.1.7 on 2025-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
