# Generated by Django 5.1.7 on 2025-04-16 04:08

import django.db.models.deletion
import django.utils.timezone
import skul_data.documents.models.document
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentcategory_alter_document_category'),
        ('schools', '0003_school_code_school_level_school_superuser_profile_and_more'),
        ('students', '0002_initial'),
        ('users', '0003_permission_role_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'permissions': [('bulk_delete_document', 'Can bulk delete documents'), ('bulk_download_document', 'Can bulk download documents')]},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name_plural': 'Document Categories'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by_superuser',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by_teacher',
        ),
        migrations.AddField(
            model_name='document',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, help_text='Roles that can access this document', to='users.role'),
        ),
        migrations.AddField(
            model_name='document',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Specific users who can access this document', related_name='allowed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='related_class',
            field=models.ForeignKey(blank=True, help_text='Optional: Class this document is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='document',
            name='related_students',
            field=models.ManyToManyField(blank=True, help_text='Optional: Students this document is associated with', to='students.student'),
        ),
        migrations.AddField(
            model_name='document',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=skul_data.documents.models.document.document_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together={('name', 'school')},
        ),
        migrations.CreateModel(
            name='DocumentShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('download_limit', models.PositiveIntegerField(blank=True, help_text='Optional: Limit number of downloads', null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
    ]
