# Generated by Django 5.1.7 on 2025-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentdocument_studentnote_studentstatuschange_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='students.student'),
        ),
    ]
