# Generated by Django 5.1.7 on 2025-04-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_parent_options_parent_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='receive_sms_notifications',
        ),
    ]
