# Generated by Django 5.1.7 on 2025-04-30 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_options_and_more'),
        ('users', '0005_remove_parent_receive_sms_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('school_admin', 'School Administrator'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('other', 'Other')], default='school_admin', max_length=20),
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Administrator',
                'verbose_name_plural': 'School Administrators',
            },
        ),
        migrations.DeleteModel(
            name='SuperUser',
        ),
    ]
