# Generated by Django 5.1.7 on 2025-05-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
