# Generated by Django 5.1.7 on 2025-06-18 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_classattendance_total_students'),
        ('users', '0013_parentnotification_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='administrator_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='administrator_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='administrator_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_admins', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('school_admin', 'School Administrator'), ('administrator', 'Administrator'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('other', 'Other')], default='school_admin', max_length=20),
        ),
        migrations.CreateModel(
            name='AdministratorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('access_level', models.CharField(choices=[('standard', 'Standard Access'), ('elevated', 'Elevated Access'), ('restricted', 'Restricted Access')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_appointed', models.DateField(default=django.utils.timezone.now)),
                ('permissions_granted', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profiles', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrator Profile',
                'verbose_name_plural': 'Administrator Profiles',
                'ordering': ['-date_appointed'],
            },
        ),
    ]
