# Generated by Django 5.1.7 on 2025-06-19 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_teacher_administrator_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratorprofile',
            name='date_appointed',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
