# Generated by Django 5.1.7 on 2025-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_administratorprofile_date_appointed'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratorprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text="User's signature image", null=True, upload_to='signatures/staff/'),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='signature',
            field=models.ImageField(blank=True, help_text="User's signature image", null=True, upload_to='signatures/staff/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='signature',
            field=models.ImageField(blank=True, help_text="Teacher's signature image", null=True, upload_to='signatures/teachers/'),
        ),
    ]
