# Generated by Django 5.1.7 on 2025-06-30 09:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0012_classattendance_total_students'),
        ('students', '0004_studentattendance'),
        ('users', '0015_alter_administratorprofile_date_appointed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('is_break', models.BooleanField(default=False)),
                ('break_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schools.school')),
            ],
            options={
                'ordering': ['day_of_week', 'order'],
                'unique_together': {('school', 'start_time', 'end_time', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_timetables', to='schools.schoolclass')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'school_class'],
                'unique_together': {('school_class', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TimetableConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('NO_TEACHER_CLASH', 'No teacher double booking'), ('NO_CLASS_CLASH', 'No class subject overlap'), ('SUBJECT_PAIRING', 'Subject pairing'), ('SCIENCE_DOUBLE', 'Science double period'), ('NO_AFTERNOON_SCIENCE', 'No science in afternoon'), ('MAX_PERIODS_PER_DAY', 'Maximum periods per day'), ('MIN_PERIODS_BETWEEN', 'Minimum periods between subjects'), ('TEACHER_AVAILABILITY', 'Teacher availability'), ('ROOM_AVAILABILITY', 'Room availability'), ('SUBJECT_PREFERENCE', 'Subject time preference')], max_length=50)),
                ('is_hard_constraint', models.BooleanField(default=True)),
                ('parameters', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_constraints', to='schools.school')),
            ],
            options={
                'ordering': ['is_hard_constraint', 'constraint_type'],
            },
        ),
        migrations.CreateModel(
            name='TimetableStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(choices=[('CBC', 'Competency Based Curriculum (CBC)'), ('8-4-4', '8-4-4 System')], default='CBC', max_length=10)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3), default=list, help_text='Days of the week when school is in session', size=None)),
                ('default_start_time', models.TimeField(default='08:00')),
                ('default_end_time', models.TimeField(default='16:00')),
                ('period_duration', models.PositiveIntegerField(default=40, help_text='Duration of each period in minutes')),
                ('break_duration', models.PositiveIntegerField(default=30, help_text='Duration of break in minutes')),
                ('lunch_duration', models.PositiveIntegerField(default=60, help_text='Duration of lunch break in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_timetable_structure', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='schools.school')),
                ('subjects', models.ManyToManyField(related_name='subject_groups', to='students.subject')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.teacher')),
            ],
            options={
                'verbose_name_plural': 'Teacher availabilities',
                'unique_together': {('teacher', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_double_period', models.BooleanField(default=False)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_timetables.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school_timetables.timetable')),
            ],
            options={
                'ordering': ['time_slot__day_of_week', 'time_slot__order'],
                'unique_together': {('timetable', 'time_slot')},
            },
        ),
    ]
