# Generated by Django 5.1.7 on 2025-07-04 09:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0013_alter_school_schooladmin'),
        ('students', '0004_studentattendance'),
        ('users', '0015_alter_administratorprofile_date_appointed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('day_order', models.PositiveIntegerField(default=1)),
                ('is_break', models.BooleanField(default=False)),
                ('break_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schools.school')),
            ],
            options={
                'ordering': ['day_order', 'order'],
                'unique_together': {('school', 'start_time', 'end_time', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_timetables', to='schools.schoolclass')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'school_class'],
                'unique_together': {('school_class', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TimetableConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('NO_TEACHER_CLASH', 'No teacher double booking (same teacher in multiple classes at same time)'), ('NO_TEACHER_SAME_SUBJECT_CLASH', 'No same subject teaching at same time by same teacher'), ('NO_CLASS_CLASH', 'No class subject overlap (one subject per class per time slot)'), ('SCIENCE_DOUBLE_PERIOD', 'Science subjects must have one double period per week (8-4-4 only)'), ('NO_CORE_AFTER_LUNCH', 'Core subjects (English, Kiswahili, Math) not after lunch'), ('NO_DOUBLE_CORE', 'No double lessons for core subjects'), ('MATH_NOT_AFTER_SCIENCE', 'Mathematics must not follow science subjects'), ('MATH_MORNING_ONLY', 'Mathematics must always be in the morning'), ('ENGLISH_KISWAHILI_SEPARATE', 'English and Kiswahili must not follow each other'), ('SUBJECT_GROUPING', "Group subjects that students don't take together"), ('MANDATORY_BREAKS', 'Include mandatory breaks (short break, long break, lunch)'), ('INCLUDE_GAMES', 'Include games period'), ('INCLUDE_PREPS', 'Include preps period (boarding schools)')], help_text='Select from predefined constraint types', max_length=50)),
                ('category', models.CharField(blank=True, choices=[('TEACHER', 'Teacher Constraints'), ('SUBJECT', 'Subject Constraints'), ('STRUCTURE', 'Structural Constraints')], max_length=10, null=True)),
                ('is_hard_constraint', models.BooleanField(default=True, help_text='Hard constraints cannot be violated. Soft constraints are preferred but not required')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Additional parameters for the constraint (e.g., subject groups)')),
                ('description', models.TextField(blank=True, help_text='Explanation of how this constraint will be applied', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_constraints', to='schools.school')),
            ],
            options={
                'verbose_name': 'Timetable Constraint',
                'verbose_name_plural': 'Timetable Constraints',
                'ordering': ['category', 'constraint_type'],
            },
        ),
        migrations.CreateModel(
            name='TimetableStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.CharField(choices=[('CBC', 'Competency Based Curriculum (CBC)'), ('8-4-4', '8-4-4 System')], default='CBC', max_length=10)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3), default=list, help_text='Days of the week when school is in session', size=None)),
                ('default_start_time', models.TimeField(default='08:00')),
                ('default_end_time', models.TimeField(default='16:00')),
                ('period_duration', models.PositiveIntegerField(default=40, help_text='Duration of each period in minutes')),
                ('break_duration', models.PositiveIntegerField(default=30, help_text='Duration of break in minutes')),
                ('lunch_duration', models.PositiveIntegerField(default=60, help_text='Duration of lunch break in minutes')),
                ('include_games', models.BooleanField(default=True, help_text='Include games period in the timetable')),
                ('games_duration', models.PositiveIntegerField(default=45, help_text='Duration of games period in minutes')),
                ('include_preps', models.BooleanField(default=False, help_text='Include preps period for boarding schools')),
                ('preps_duration', models.PositiveIntegerField(default=60, help_text='Duration of preps period in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_timetable_structure', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='schools.school')),
                ('subjects', models.ManyToManyField(related_name='subject_groups', to='students.subject')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.teacher')),
            ],
            options={
                'verbose_name_plural': 'Teacher availabilities',
                'ordering': ['teacher', 'day_of_week'],
                'unique_together': {('teacher', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_double_period', models.BooleanField(default=False)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_timetables.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school_timetables.timetable')),
            ],
            options={
                'ordering': ['time_slot__day_of_week', 'time_slot__order'],
                'unique_together': {('timetable', 'time_slot')},
            },
        ),
    ]
