# Generated by Django 5.1.7 on 2025-11-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_timetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day_order', 'start_time', 'order']},
        ),
    ]
