# Generated by Django 5.1.7 on 2025-06-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_timetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day_order', 'order']},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
