# Generated by Django 5.1.7 on 2025-06-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
