# Generated by Django 5.1.7 on 2025-06-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_started',
        ),
    ]
